version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    image: mariadb:inception
    env_file: .env
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    image: nginx:inception
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    container_name : wordpress
    build:
      context : ./requirements/wordpress
      dockerfile: ./Dockerfile
    image: wordpress:inception
    env_file: .env
    networks:
      - inception
    expose:
      - "9000"
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type : bind
      o: 'bind'
      device: /home/nlorion/data/wordpress-data
  mariadb-data:
    driver: local
    driver_opts:
      type : bind
      o: 'bind'
      device: /home/nlorion/data/mariadb-data

networks:
  inception:
    name: inception
    driver: bridge
