version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context : requirements/nginx
      dockerfile: ./Dockerfile
    image: nginx:inception
    env_file: .env
    networks: inception
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress
  wordpress:
    container_name : wordpress
    build:
      context : ./requirements/wordpress/
      dockerfile: ./Dockerfile
    image: wordpress:inception
    env_file: .env
    networks: inception
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type : 'none'
      o: 'bind'
      device: ${DATA_PATH}/wordpress-data
