version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context : requirements/nginx/
      dockerfile: ./Dockerfile
    image: nginx:inception
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile
    image: mariadb:inception
    env_file: .env
    networks:
      - inception
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql/

  wordpress:
    container_name : wordpress
    build:
      context : ./requirements/wordpress/
      dockerfile: ./Dockerfile
    image: wordpress:inception
    env_file: .env
    networks:
      - inception
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - mariadb

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type : 'none'
      o: 'bind'
      device: ${DATA_PATH}/mariadb-data
  wordpress-data:
    driver: local
    driver_opts:
      type : 'none'
      o: 'bind'
      device: ${DATA_PATH}/wordpress-data

networks:
  inception:
    name: inception
    driver: bridge
