version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context : requirements/nginx
      dockerfile: ./Dockerfile
    image: nginx:inception
    ports:
      - "443:443"
    restart: always