version: '3.7'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx:inception
    environment:
      NGINX_HOST: ${NGINX_HOST}
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile
    image: mariadb:inception
    environment:
      DB_ROOT_USER: ${DB_ROOT_USER}
      DB_ROOT_PASS: ${DB_ROOT_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    env_file: .env
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - mariadb-data:/var/lib/mysql/

  wordpress:
    container_name : wordpress
    build:
      context : ./requirements/wordpress/
      dockerfile: ./Dockerfile
    image: wordpress:inception
    environment:
      NGINX_HOST: ${NGINX_HOST}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      WP_DATABASE: ${WP_DATABASE}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_USER_MAIL: ${WP_USER_MAIL}
    env_file: .env
    networks:
      - inception
    ports:
      - "9000:9000"
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/
    depends_on:
      - mariadb

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type : 'none'
      o: 'bind'
      device: /home/nlorion/Desktop/nlorion/wordpress-data
  mariadb-data:
    driver: local
    driver_opts:
      type : 'none'
      o: 'bind'
      device: /home/nlorion/Desktop/nlorion/mariadb-data

networks:
  inception:
    name: inception
    driver: bridge
