version: '3'

services:
  nginx:
    image: alpine:3.17
    container_name: nginx
    build:
      image: nginx:inception
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./requirements/nginx/www:/usr/share/nginx/html:ro
      - ./requirements/nginx/log:/var/log/nginx
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d
    restart: always