version: '3'

services:
  nginx:
    image: alpine:3.17
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/app
      - ./nginx/www:/usr/share/nginx/html:ro
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d
    restart: always
    # volumes:
    #   - ./nginx/conf:/etc/nginx/conf.d/:ro
    #   - ./certbot/www:/var/www/certbot/:ro
    # certbot:
    #   image: certbot/certbot:2.2
    #   volumes:
    #     - ./certbot/www/:/var/www/certbot/:rw
