version: '3'

services:
  nginx:
    image: alpine:3.17
    container_name: nginx
    volumes:
      - .:/app
      - ./requirements/nginx/www:/usr/share/nginx/html:ro
      - ./requirements/nginx/log:/var/log/nginx
      - ./requirements/conf/nginx.conf:/etc/nginx/conf.d
    ports:
      - "127.0.0.1:80:80"
